"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from urllib.parse import urlparse
from dotenv import load_dotenv
from celery.schedules import crontab
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

LOG_DIR = Path(os.getenv("LOG_DIR", "logs"))
if not LOG_DIR.is_absolute():
    LOG_DIR = BASE_DIR / LOG_DIR
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
LOG_BACKUP_COUNT = int(os.getenv("LOG_BACKUP_COUNT", "14"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

# Chave AES-256 (base64 de 32 bytes) usada para criptografar campos sensíveis
# em repouso — ver apps/core/crypto.py. Validada de forma lazy no primeiro
# uso (ImproperlyConfigured), não no import das settings, para não quebrar
# comandos que não tocam em campos criptografados.
FIELD_ENCRYPTION_KEY = os.getenv("FIELD_ENCRYPTION_KEY", "")

# POWER BI
POWER_BI_SERVICE_TOKEN = os.getenv("POWER_BI_SERVICE_TOKEN", "")
POWER_BI_RATE_LIMIT = os.getenv("POWER_BI_RATE_LIMIT", "100/hour")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,backend").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "django_celery_beat",
    "corsheaders",
    "drf_spectacular",
    "apps.core",
    "apps.sgp",
    "apps.sgf",
    "apps.sgd",
    "apps.sgs",
    "apps.sge",
    "apps.sca",
]

AUTH_USER_MODEL = "core.User"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "apps.core.middleware.ContentSecurityPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.core.middleware.SessionContextMiddleware",
    "apps.core.middleware.AuditContextMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "setup.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "setup.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

# Password hashing — bcrypt custo 12 (Arq. §8)
PASSWORD_HASHERS = [
    "setup.hashers.BCrypt12PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",  # fallback para senhas antigas
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = Path(os.getenv("STATIC_ROOT", BASE_DIR / "staticfiles"))
if not STATIC_ROOT.is_absolute():
    STATIC_ROOT = BASE_DIR / STATIC_ROOT

MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", BASE_DIR / "media"))
if not MEDIA_ROOT.is_absolute():
    MEDIA_ROOT = BASE_DIR / MEDIA_ROOT

DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", "10485760")
)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv("FILE_UPLOAD_MAX_MEMORY_SIZE", "10485760")
)

STORAGE_BACKEND = os.getenv("STORAGE_BACKEND", "local")
R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID", "")
R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY", "")
R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME", "pdhc-iii")
R2_ENDPOINT_URL = os.getenv("R2_ENDPOINT_URL", "")
R2_PUBLIC_URL = os.getenv("R2_PUBLIC_URL", "")
LOCAL_STORAGE_UPLOAD_URL = os.getenv(
    "LOCAL_STORAGE_UPLOAD_URL",
    "/api/v1/storage/local-upload/",
)


def _origin_from_url(value):
    parsed = urlparse(value or "")
    if not parsed.scheme or not parsed.netloc:
        return ""
    return f"{parsed.scheme}://{parsed.netloc}"


CSP_CONNECT_SRC = [
    source
    for source in [
        "'self'",
        "https://*.r2.cloudflarestorage.com",
        _origin_from_url(R2_ENDPOINT_URL),
        _origin_from_url(R2_PUBLIC_URL),
    ]
    if source
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "apps.core.permissions.IsAuthenticatedActiveAccess",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/min",
        "user": "1000/min",
        "auth_login": "5/5min",
        "auth_refresh": "10/5min",
        "auth_password_reset_confirm": "3/5min",
        "auth_password_reset_email": "3/hour",
        "auth_password_reset_ip": "5/hour",
        "notification_unread_count": "60/min",
        "power_bi_service": POWER_BI_RATE_LIMIT,
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "setup.exceptions.custom_exception_handler",
    "NUM_PROXIES": 1,  # Railway usa 1 load balancer na frente
    # Isso faz o SimpleRateThrottle usar X-Forwarded-For
    # corretamente sem confiar em IPs intermediários injetáveis
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "PDHC API",
    "DESCRIPTION": "API do Programa de Desenvolvimento Humano de Crianças e Adolescentes (PDHC)",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
    },
}

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]

# CONFIGURAÇÕES DO CELERY
CELERY_BROKER_URL = f"redis://{os.getenv('REDIS_HOST', 'redis')}:{os.getenv('REDIS_PORT', '6379')}/0"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_TIMEZONE = "America/Fortaleza"

CELERY_BEAT_SCHEDULE = {
    "cleanup_expired_tokens": {
        "task": "setup.tasks.cleanup_expired_tokens",
        "schedule": crontab(hour=2, minute=0),  # todo dia às 2h da manhã
    },
    "check_acao_progress_alert": {
        "task": "sgp.tasks.check_acao_progress_alert",
        "schedule": crontab(hour=12, minute=0),  # diariamente ao meio-dia
    },
    "export_to_power_bi": {
        "task": "sgp.tasks.export_to_power_bi",
        "schedule": crontab(minute=0),  # a cada hora
    },
}

# E-MAIL
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@pdhc.ufersa.edu.br")

FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "https://pdhc.ufersa.edu.br")

# GOOGLE CALENDAR
GOOGLE_CALENDAR_SERVICE_ACCOUNT_INFO = os.getenv("GOOGLE_CALENDAR_SERVICE_ACCOUNT_INFO", "")
GOOGLE_CALENDAR_SERVICE_ACCOUNT_FILE = os.getenv("GOOGLE_CALENDAR_SERVICE_ACCOUNT_FILE", "")
GOOGLE_CALENDAR_DELEGATED_USER = os.getenv("GOOGLE_CALENDAR_DELEGATED_USER", "")

# SENTRY
SENTRY_DSN = os.getenv("SENTRY_DSN", "")
if SENTRY_DSN:
    try:
        import sentry_sdk

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            send_default_pii=False,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0")),
        )
    except ImportError:
        pass

# CACHES : UTIZEI O BANCO 1 DO REDIS POIS O BANCO 0 É O CELERY QUEM ESTÁ USANDO.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{os.getenv('REDIS_HOST', 'redis')}:{os.getenv('REDIS_PORT', '6379')}/1",
    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s [%(name)s] %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "app_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "app.log"),
            "when": "midnight",
            "backupCount": LOG_BACKUP_COUNT,
            "encoding": "utf-8",
            "formatter": "standard",
        },
        "security_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "security.log"),
            "when": "midnight",
            "backupCount": int(os.getenv("SECURITY_LOG_BACKUP_COUNT", "90")),
            "encoding": "utf-8",
            "formatter": "standard",
        },
        "audit_events_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "audit-events.log"),
            "when": "midnight",
            "backupCount": int(os.getenv("AUDIT_LOG_BACKUP_COUNT", "90")),
            "encoding": "utf-8",
            "formatter": "standard",
        },
        "celery_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "celery.log"),
            "when": "midnight",
            "backupCount": LOG_BACKUP_COUNT,
            "encoding": "utf-8",
            "formatter": "standard",
        },
        "errors_file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOG_DIR / "errors.log"),
            "when": "midnight",
            "backupCount": int(os.getenv("ERROR_LOG_BACKUP_COUNT", "30")),
            "encoding": "utf-8",
            "formatter": "standard",
            "level": "ERROR",
        },
    },
    "loggers": {
        "apps": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "setup": {
            "handlers": ["console", "app_file", "errors_file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "security": {
            "handlers": ["console", "security_file", "errors_file"],
            "level": os.getenv("SECURITY_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "audit_events": {
            "handlers": ["console", "audit_events_file", "errors_file"],
            "level": os.getenv("AUDIT_EVENT_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "apps.core.tasks": {
            "handlers": ["console", "celery_file", "errors_file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "errors_file"],
            "level": "ERROR",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console", "errors_file"],
        "level": "WARNING",
    },
}
