# Generated by Django 6.0.4 on 2026-09-21 19:01

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sgp', '0028_alter_budgettransaction_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('justificativa', models.TextField(blank=True, default='', verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('submetida', 'Submetida'), ('devolvida', 'Devolvida'), ('pre_autorizada', 'Pré-autorizada'), ('autorizada', 'Autorizada'), ('em_atendimento', 'Em atendimento'), ('concluida', 'Concluída'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], db_index=True, default='rascunho', max_length=20, verbose_name='Status')),
                ('despesa_posterior', models.BooleanField(default=False, help_text='Capturado na criação quando a atividade vinculada já estava em Em andamento/Concluída/Concluída sem evidência — sinaliza ao aprovador, não é recalculado depois.', verbose_name='Despesa posterior à execução')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to='sgp.activity', verbose_name='Atividade')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('pre_autorizacao', 'Pré-autorização'), ('autorizacao', 'Autorização'), ('atendimento', 'Atendimento')], max_length=20, verbose_name='Etapa')),
                ('acao', models.CharField(choices=[('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('devolvido', 'Devolvido'), ('atendido', 'Atendido')], max_length=20, verbose_name='Ação')),
                ('justificativa', models.TextField(blank=True, default='', verbose_name='Justificativa')),
                ('excedente_autorizado', models.BooleanField(default=False, help_text='Marcado quando a UGP autoriza excedendo limite individual ou pool territorial (RF16).', verbose_name='Excedente autorizado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_demanda_decididas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas', to='sgd.demand', verbose_name='Demanda')),
            ],
            options={
                'verbose_name': 'Etapa de Aprovação',
                'verbose_name_plural': 'Etapas de Aprovação',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DemandDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_key', models.CharField(max_length=512, verbose_name='Key do arquivo (R2)')),
                ('arquivo_url', models.URLField(max_length=1024, verbose_name='URL pública do arquivo')),
                ('tipo', models.CharField(choices=[('suporte', 'Documento de suporte'), ('ata', 'Ata'), ('comprovante', 'Comprovante'), ('cotacao', 'Cotação')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome original do arquivo')),
                ('content_type', models.CharField(default='application/pdf', max_length=100, verbose_name='Content-Type')),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Tamanho em bytes')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='sgd.demand', verbose_name='Demanda')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_demanda_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento da Demanda',
                'verbose_name_plural': 'Documentos da Demanda',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='DemandIndividualLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_limite', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Limite (R$)')),
                ('valor_comprometido', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Comprometido (R$)')),
                ('valor_executado', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Executado (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limites_individuais_sgd_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limites_individuais', to='sgp.budgetrubrica', verbose_name='Rubrica')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_individuais_sgd', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Limite Individual de Demanda',
                'verbose_name_plural': 'Limites Individuais de Demanda',
                'ordering': ['solicitante', 'rubrica'],
            },
        ),
        migrations.CreateModel(
            name='DemandRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diaria', 'Diárias'), ('passagem', 'Passagens Aéreas'), ('veiculo', 'Locação de Veículo'), ('grafico', 'Material Gráfico'), ('alimentacao', 'Alimentação'), ('equipamento', 'Aquisição de Equipamentos')], max_length=20, verbose_name='Tipo')),
                ('campos_json', models.JSONField(default=dict, verbose_name='Campos do formulário')),
                ('beneficiario_cpf', apps.core.fields.EncryptedCharField(blank=True, default=None, max_length=14, null=True, verbose_name='CPF do beneficiário (criptografado)')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Estimado (R$)')),
                ('valor_autorizado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor Autorizado (R$)')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor Pago (R$)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='sgd.demand', verbose_name='Demanda')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_sgd', to='sgp.budgetrubrica', verbose_name='Rubrica')),
            ],
            options={
                'verbose_name': 'Solicitação de Recurso',
                'verbose_name_plural': 'Solicitações de Recurso',
                'ordering': ['demanda', 'ordem'],
            },
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['activity'], name='idx_demand_activity'),
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['status', 'solicitante'], name='idx_demand_status_solic'),
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['status', '-criado_em'], name='idx_demand_status_criado'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['demanda', 'criado_em'], name='idx_apprstep_demanda_criado'),
        ),
        migrations.AddIndex(
            model_name='demanddocument',
            index=models.Index(fields=['demanda', 'ativo'], name='idx_demanddoc_demanda_ativo'),
        ),
        migrations.AddIndex(
            model_name='demanddocument',
            index=models.Index(fields=['demanda', 'tipo', 'ativo'], name='idx_demanddoc_demanda_tipo'),
        ),
        migrations.AddConstraint(
            model_name='demandindividuallimit',
            constraint=models.UniqueConstraint(fields=('solicitante', 'rubrica'), name='unique_demandindividuallimit_solicitante_rubrica'),
        ),
        migrations.AddIndex(
            model_name='demandrequest',
            index=models.Index(fields=['demanda'], name='idx_demandrequest_demanda'),
        ),
        migrations.AddIndex(
            model_name='demandrequest',
            index=models.Index(fields=['rubrica', 'valor_autorizado'], name='idx_demreq_rubrica_autoriz'),
        ),
    ]
