# Generated by Django 6.0.4 on 2026-09-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgd', '0002_seed_configuracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanddocument',
            name='fornecedor',
            field=models.CharField(blank=True, default='', help_text="Obrigatório para tipo='cotacao' — exigido para checar distinção entre as 3 cotações mínimas.", max_length=255, verbose_name='Fornecedor'),
        ),
    ]
