# Generated by Django 6.0.4 on 2026-09-24 21:00

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def preencher_com_atualizado_em(apps, schema_editor):
    # Melhor aproximação disponível pro histórico: sem ela, toda demanda
    # existente nasceria com "status alterado agora" e o alerta de
    # inatividade ficaria mudo por 5 dias úteis após o deploy.
    Demand = apps.get_model("sgd", "Demand")
    Demand.objects.update(status_alterado_em=F("atualizado_em"))


class Migration(migrations.Migration):

    dependencies = [
        ('sgd', '0004_rls_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='status_alterado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Última mudança de status — referência do alerta de inatividade. Diferente de atualizado_em, não muda em edições que mantêm o status.', verbose_name='Status alterado em'),
        ),
        migrations.RunPython(preencher_com_atualizado_em, migrations.RunPython.noop),
    ]
