# Generated by Django 6.0.4 on 2026-09-30 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgd', '0005_demand_status_alterado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='numero_processo',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Número do processo de pagamento informado pelo Arlo na importação de retorno.', max_length=64, verbose_name='Número do processo'),
        ),
        migrations.CreateModel(
            name='ArloImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('exportacao', 'Exportação'), ('importacao', 'Importação')], max_length=12, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('falhou', 'Falhou')], db_index=True, default='pendente', max_length=12, verbose_name='Status')),
                ('arquivo_key', models.CharField(max_length=512, verbose_name='Key do arquivo')),
                ('arquivo_url', models.URLField(max_length=1024, verbose_name='URL do arquivo')),
                ('nome_original', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome original do arquivo')),
                ('operado_em', models.DateTimeField(auto_now_add=True, verbose_name='Operado em')),
                ('total_registros', models.PositiveIntegerField(default=0, verbose_name='Total de registros')),
                ('registros_ok', models.PositiveIntegerField(default=0, verbose_name='Registros processados com sucesso')),
                ('erros_json', models.JSONField(blank=True, default=list, help_text='Lista de {linha, erro, campo?} — linhas com erro não interrompem as válidas.', verbose_name='Erros por linha')),
                ('operado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_arlo', to=settings.AUTH_USER_MODEL, verbose_name='Operado por')),
            ],
            options={
                'verbose_name': 'Operação Arlo',
                'verbose_name_plural': 'Operações Arlo',
                'ordering': ['-operado_em'],
                'indexes': [models.Index(fields=['tipo', '-operado_em'], name='idx_arlo_tipo_operado')],
            },
        ),
    ]
