# Generated by Django 6.0.4 on 2026-10-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgd', '0007_seed_arlo_mapeamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='arloimport',
            name='ip_origem',
            field=models.GenericIPAddressField(blank=True, help_text='IP de quem enviou o arquivo — repassado à auditoria das movimentações feitas pela task.', null=True, verbose_name='IP de origem'),
        ),
    ]
