version: "3.9"

services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend.
    command: >- # o backend deve esperar o db estar disponivel para inicializar
      sh -c "until python -c \"import socket; socket.create_connection(('db', 5432), 2).close()\"; do sleep 1; done;
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8080:8000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    command: celery -A setup worker --loglevel=info
    depends_on:
      - backend
      - redis

  celery_beat:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    command: celery -A setup beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=500
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend

volumes:
  postgres_data:
