# Generated by Django 6.0.4 on 2026-04-26 20:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('perfil', models.CharField(choices=[('agricultor_beneficiario', 'Agricultor / Beneficiário'), ('tecnico_campo_adt_acr', 'ADT / ACR — Técnico de campo'), ('articulador_estadual', 'Articulador Estadual'), ('ugp_coordenacao', 'UGP — Coordenação territorial'), ('fgd_equipe_fundacao', 'FGD — Equipe Fundação'), ('super_admin', 'UFERSA / Equipe técnica (Super Admin)')], max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['ativo', 'ultimo_login'], name='core_usr_ativo_login_idx')],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(choices=[('PE', 'PE'), ('PB', 'PB'), ('AL', 'AL'), ('RN', 'RN'), ('MA', 'MA'), ('BA', 'BA'), ('MG', 'MG')], max_length=2, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Territorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('articulador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territorios', to=settings.AUTH_USER_MODEL)),
                ('estados', models.ManyToManyField(blank=True, related_name='territorios', to='core.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo_ibge', models.CharField(max_length=7, unique=True)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('populacao_total', models.PositiveIntegerField(blank=True, null=True)),
                ('populacao_rural', models.PositiveIntegerField(blank=True, null=True)),
                ('idh', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('perc_extremamente_pobres', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('benef_programa_agri_familiar', models.PositiveIntegerField(blank=True, null=True)),
                ('estab_agri_familiar', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='core.estado')),
                ('territorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipios', to='core.territorio')),
            ],
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('zona', models.CharField(choices=[('rural', 'Rural'), ('urbana', 'Urbana')], max_length=10)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunidades', to='core.municipio')),
                ('territorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunidades', to='core.territorio')),
            ],
        ),
    ]
