# Generated by Django 6.0.4 on 2026-05-04 22:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('perfil', models.CharField(choices=[('agricultor_beneficiario', 'Agricultor / Beneficiário'), ('tecnico_campo_adt_acr', 'ADT / ACR — Técnico de campo'), ('articulador_estadual', 'Articulador Estadual'), ('ugp_coordenacao', 'UGP — Coordenação territorial'), ('fgd_equipe_fundacao', 'FGD — Equipe Fundação'), ('super_admin', 'UFERSA / Equipe técnica (Super Admin)')], max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['ativo', 'ultimo_login'], name='core_usr_ativo_login_idx')],
            },
        ),
        migrations.AlterField(
            model_name='territorio',
            name='articulador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territorios', to=settings.AUTH_USER_MODEL),
        ),
    ]
