# Generated by Django 6.0.4 on 2026-05-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='territorios',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.territory'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
