# Generated by Django 6.0.4 on 2026-05-13 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='core.role', verbose_name='Perfil / Role')),
                ('territorio', models.ForeignKey(blank=True, help_text='Se nulo, acesso a todos os territórios do perfil.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.territory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
                'ordering': ['user'],
            },
        ),
    ]
