# Generated by Django 6.0.4 on 2026-05-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('motivo_falha', models.CharField(blank=True, choices=[('INVALID_CREDENTIALS', 'Credenciais inválidas'), ('INACTIVE_USER', 'Usuário inativo'), ('RATE_LIMITED', 'Limite de tentativas atingido'), ('INVALID_FORMAT', 'Formato inválido')], max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Tentativa de Login',
                'verbose_name_plural': 'Tentativas de Login',
                'ordering': ['-timestamp'],
            },
        ),
    ]
