# Generated by Django 6.0.4 on 2026-05-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_loginattempt'),
        ('core', '0008_userprofile'),
    ]

    operations = [
    ]
