# Generated by Django 6.0.4 on 2026-05-19 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_0008_loginattempt_0008_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'E-mail'), ('push', 'Push'), ('whatsapp', 'WhatsApp'), ('in_app', 'In-App')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('link', models.URLField(blank=True, default='')),
                ('modulo_origem', models.CharField(blank=True, default='', max_length=100)),
                ('evento', models.CharField(blank=True, default='', max_length=100)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('lido_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('falhou', 'Falhou')], default='pendente', max_length=20)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-enviado_em'],
                'indexes': [models.Index(fields=['user', 'lido_em'], name='idx_notif_user_lido_em'), models.Index(fields=['user', '-enviado_em'], name='idx_notif_user_enviado_em')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('push', 'Push'), ('whatsapp', 'WhatsApp'), ('in_app', 'In-App')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
                'constraints': [models.UniqueConstraint(fields=('user', 'tipo_evento', 'canal'), name='uq_notifpref_user_evento_canal')],
            },
        ),
    ]
