# Generated by Django 6.0.4 on 2026-05-21 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('tipo', models.CharField(choices=[('ASSOCIACAO', 'Associação'), ('COOPERATIVA', 'Cooperativa'), ('FUNDACAO', 'Fundação'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('contato', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.municipality')),
                ('territorios', models.ManyToManyField(blank=True, related_name='organizations', to='core.territory')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['ativa'], name='core_organi_ativa_107fec_idx'), models.Index(fields=['tipo'], name='core_organi_tipo_3664b2_idx')],
            },
        ),
    ]
