# Generated by Django 6.0.4 on 2026-05-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auditlog_rebuild'),
        ('core', '0011_organization'),
    ]

    operations = [
    ]
