# Generated by Django 6.0.4 on 2026-05-25 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_0010_auditlog_rebuild_0011_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='acao',
            field=models.CharField(help_text='Verbo da operação: CREATE, UPDATE, DELETE, LOGIN, LOGOUT…', max_length=50, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entidade',
            field=models.CharField(help_text="Nome do model afetado (ex: 'Projeto', 'User').", max_length=100, verbose_name='Entidade'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entidade_id',
            field=models.CharField(blank=True, default='', help_text='PK do registro afetado. Texto para suportar UUIDs e inteiros.', max_length=255, verbose_name='ID da Entidade'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='modulo',
            field=models.CharField(help_text="App Django responsável pela ação (ex: 'sgp', 'core').", max_length=100, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='Identificação do navegador ou cliente HTTP.', verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='valores_anteriores',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot do estado antes da alteração. Vazio em CREATE.', verbose_name='Valores Anteriores'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='valores_novos',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot do estado após a alteração. Vazio em DELETE.', verbose_name='Valores Novos'),
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=255, unique=True)),
                ('valor', models.TextField()),
                ('tipo', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], max_length=20)),
                ('descricao', models.TextField(blank=True, default='')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'ordering': ['chave'],
            },
        ),
    ]
