# Generated by Django 6.0.4 on 2026-05-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_system_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
