# Generated by Django 6.0.4 on 2026-07-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0014_unifica_user_profile')]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='acao',
            field=models.CharField(help_text='Verbo da operação: CREATE, UPDATE, DELETE, LOGIN, LOGOUT…', max_length=50, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entidade',
            field=models.CharField(help_text="Nome do model afetado (ex: 'Projeto', 'User').", max_length=100, verbose_name='Entidade'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entidade_id',
            field=models.CharField(blank=True, default='', help_text='PK do registro afetado. Texto para suportar UUIDs e inteiros.', max_length=255, verbose_name='ID da Entidade'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='modulo',
            field=models.CharField(help_text="App Django responsável pela ação (ex: 'sgp', 'core').", max_length=100, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='Identificação do navegador ou cliente HTTP.', verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='valores_anteriores',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot do estado antes da alteração. Vazio em CREATE.', verbose_name='Valores Anteriores'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='valores_novos',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot do estado após a alteração. Vazio em DELETE.', verbose_name='Valores Novos'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
