# Generated by Django 6.0.4 on 2026-08-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_google_calendar_config'),
        ('core', '0016_user_acesso_revogado'),
    ]

    operations = [
    ]
