# Generated by Django 6.0.4 on 2026-08-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_seed_import_record'),
        ('core', '0018_seed_sca_sync_alerta_dias'),
    ]

    operations = [
    ]
