# Generated by Django 6.0.4 on 2026-09-01 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20260828_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_mascarado', models.CharField(max_length=16)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_bi_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de administração do Power BI',
                'verbose_name_plural': 'Tokens de administração do Power BI',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='powerbitoken',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('ativo',), name='uniq_power_bi_token_ativo'),
        ),
    ]
