# Generated by Django 6.0.4 on 2026-07-21 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_alter_auditlog_and_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunidades_criadas', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunidades', to='core.municipality')),
            ],
            options={
                'verbose_name': 'Comunidade',
                'verbose_name_plural': 'Comunidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('nome_cientifico', models.CharField(blank=True, default='', max_length=160)),
                ('categoria', models.CharField(choices=[('graos', 'Grãos'), ('raizes', 'Raízes'), ('frutas', 'Frutas'), ('hortalicas', 'Hortaliças'), ('leguminosas', 'Leguminosas'), ('oleaginosas', 'Oleaginosas'), ('fibrosas', 'Fibrosas'), ('forrageiras', 'Forrageiras'), ('ornamentais', 'Ornamentais'), ('medicinais', 'Medicinais'), ('outras', 'Outras')], max_length=30)),
                ('ciclo', models.CharField(choices=[('anual', 'Anual'), ('perene', 'Perene'), ('bianual', 'Bianual')], max_length=10)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cultura',
                'verbose_name_plural': 'Culturas',
                'ordering': ['categoria', 'nome'],
                'indexes': [models.Index(fields=['categoria', 'nome'], name='idx_cultura_categoria_nome')],
            },
        ),
        migrations.CreateModel(
            name='EspecieAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('bovino', 'Bovino'), ('suino', 'Suíno'), ('ovino', 'Ovino'), ('caprino', 'Caprino'), ('aves', 'Aves'), ('equino', 'Equino'), ('piscicultura', 'Piscicultura'), ('apicultura', 'Apicultura'), ('outros', 'Outros')], max_length=30)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Espécie Animal',
                'verbose_name_plural': 'Espécies Animais',
                'ordering': ['categoria', 'nome'],
                'indexes': [models.Index(fields=['categoria', 'nome'], name='idx_especie_categoria_nome')],
            },
        ),
        migrations.CreateModel(
            name='MembroFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('genero', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Feminino'), (3, 'Outro'), (4, 'Não Informado')], null=True, verbose_name='Gênero')),
                ('cor_raca', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Branca'), (2, 'Preta'), (3, 'Parda'), (4, 'Amarela'), (5, 'Indígena'), (6, 'Não Informado')], null=True, verbose_name='Cor/Raça')),
                ('cpf', models.CharField(blank=True, default='', max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, default='', max_length=20, verbose_name='RG')),
                ('nis', models.CharField(blank=True, default='', max_length=11, verbose_name='NIS')),
                ('caf', models.CharField(blank=True, default='', max_length=30, verbose_name='CAF')),
                ('parentesco', models.CharField(choices=[('titular', 'Titular'), ('conjuge', 'Cônjuge'), ('filho', 'Filho(a)'), ('enteado', 'Enteado(a)'), ('pai', 'Pai'), ('mae', 'Mãe'), ('irmao', 'Irmão(ã)'), ('avo', 'Avô(ó)'), ('neto', 'Neto(a)'), ('outro', 'Outro')], max_length=20, verbose_name='Parentesco')),
                ('escola', models.CharField(blank=True, default='', max_length=255, verbose_name='Escola')),
                ('seguridade_social', models.JSONField(blank=True, default=list, verbose_name='Seguridade Social')),
                ('saude', models.JSONField(blank=True, default=list, verbose_name='Condições de Saúde')),
                ('escolaridade', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sem instrução'), (2, 'Fundamental incompleto'), (3, 'Fundamental completo'), (4, 'Médio incompleto'), (5, 'Médio completo'), (6, 'Superior incompleto'), (7, 'Superior completo'), (8, 'Pós-graduação'), (9, 'Não Informado')], null=True, verbose_name='Escolaridade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Membro da Família',
                'verbose_name_plural': 'Membros da Família',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(blank=True, default='', max_length=100, verbose_name='Apelido')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp')),
                ('celular', models.CharField(blank=True, default='', max_length=20, verbose_name='Celular')),
                ('internet', models.BooleanField(default=False, verbose_name='Acesso à Internet')),
                ('dispositivo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Computador'), (2, 'Notebook'), (3, 'Tablet'), (4, 'Smartphone'), (5, 'Não possui'), (6, 'Outro')], null=True, verbose_name='Dispositivo')),
                ('cep', models.CharField(blank=True, default='', max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, default='', max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, default='', max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, default='', max_length=255, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, default='', max_length=255, verbose_name='Bairro')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('pct', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não Informado')], null=True, verbose_name='PCT')),
                ('posse_terra', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Própria'), (2, 'Alugada'), (3, 'Cedida'), (4, 'Ocupação'), (5, 'Posse tradicional'), (6, 'Não Informado')], null=True, verbose_name='Posse da Terra')),
                ('area_terra_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área da Terra (ha)')),
                ('situacao_moradia', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Própria'), (2, 'Alugada'), (3, 'Cedida'), (4, 'Ocupação'), (5, 'Financiada'), (6, 'Não Informado')], null=True, verbose_name='Situação da Moradia')),
                ('tipo_moradia', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Casa'), (2, 'Apartamento'), (3, 'Cômodo'), (4, 'Barraca'), (5, 'Outro'), (6, 'Não Informado')], null=True, verbose_name='Tipo de Moradia')),
                ('material_construcao', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Alvenaria'), (2, 'Madeira'), (3, 'Taipa'), (4, 'Pedra'), (5, 'Misto'), (6, 'Outro'), (7, 'Não Informado')], null=True, verbose_name='Material de Construção')),
                ('num_comodos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Cômodos')),
                ('energia', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não Informado')], null=True, verbose_name='Energia')),
                ('agua', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Rede pública'), (2, 'Poço artesiano'), (3, 'Poço raso'), (4, 'Nascente'), (5, 'Carro-pipa'), (6, 'Chuva'), (7, 'Outro'), (8, 'Não Informado')], null=True, verbose_name='Água')),
                ('numero_dap', models.CharField(blank=True, default='', max_length=30, verbose_name='Número DAP')),
                ('nis', models.CharField(blank=True, default='', max_length=11, verbose_name='NIS')),
                ('seguridade_social', models.JSONField(blank=True, default=list, verbose_name='Seguridade Social')),
                ('foto_url', models.URLField(blank=True, default='', verbose_name='URL da Foto')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('comunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upfs', to='sgp.comunidade', verbose_name='Comunidade')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upfs', to='core.municipality', verbose_name='Município')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upfs', to='sgp.projeto', verbose_name='Projeto')),
                ('territorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upfs', to='core.territory', verbose_name='Território')),
                ('titular', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='upf_titular', to='sgp.membrofamilia', verbose_name='Titular')),
            ],
            options={
                'verbose_name': 'UPF',
                'verbose_name_plural': 'UPFs',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='membrofamilia',
            name='upf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='sgp.upf', verbose_name='UPF'),
        ),
        migrations.CreateModel(
            name='UPFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dap_caf', 'DAP/CAF'), ('contrato', 'Contrato'), ('laudo', 'Laudo'), ('identidade', 'Identidade'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('arquivo_key', models.CharField(max_length=512, verbose_name='Key do Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content-Type')),
                ('tamanho_bytes', models.PositiveBigIntegerField(verbose_name='Tamanho em Bytes')),
                ('data_documento', models.DateField(verbose_name='Data do Documento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_upf_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('upf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='sgp.upf', verbose_name='UPF')),
            ],
            options={
                'verbose_name': 'Documento da UPF',
                'verbose_name_plural': 'Documentos da UPF',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='comunidade',
            index=models.Index(fields=['municipio'], name='sgp_comunid_municip_65f115_idx'),
        ),
        migrations.AddConstraint(
            model_name='comunidade',
            constraint=models.UniqueConstraint(condition=models.Q(('ativa', True)), fields=('nome', 'municipio'), name='unique_comunidade_ativa_por_municipio'),
        ),
        migrations.AddIndex(
            model_name='upf',
            index=models.Index(fields=['municipio'], name='idx_upf_municipio'),
        ),
        migrations.AddIndex(
            model_name='upf',
            index=models.Index(fields=['territorio'], name='idx_upf_territorio'),
        ),
        migrations.AddIndex(
            model_name='upf',
            index=models.Index(fields=['projeto'], name='idx_upf_projeto'),
        ),
        migrations.AddIndex(
            model_name='upf',
            index=models.Index(fields=['comunidade'], name='idx_upf_comunidade'),
        ),
        migrations.AddIndex(
            model_name='membrofamilia',
            index=models.Index(fields=['upf'], name='idx_membro_upf'),
        ),
        migrations.AddConstraint(
            model_name='membrofamilia',
            constraint=models.UniqueConstraint(condition=models.Q(('parentesco', 'titular')), fields=('upf',), name='unique_titular_por_upf'),
        ),
        migrations.AddIndex(
            model_name='upfdocument',
            index=models.Index(fields=['upf', '-criado_em'], name='idx_upfdoc_upf_criado'),
        ),
        migrations.AddIndex(
            model_name='upfdocument',
            index=models.Index(fields=['arquivo_key'], name='idx_upfdoc_arquivo_key'),
        ),
    ]
