# Generated by Django 6.0.4 on 2026-07-02 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(blank=True, default='', max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, default='', max_length=20, verbose_name='RG')),
                ('nis', models.CharField(blank=True, default='', max_length=11, verbose_name='NIS')),
                ('caf', models.CharField(blank=True, default='', max_length=30, verbose_name='CAF')),
                ('parentesco', models.CharField(choices=[('titular', 'Titular'), ('conjuge', 'Cônjuge'), ('filho', 'Filho(a)'), ('enteado', 'Enteado(a)'), ('pai', 'Pai'), ('mae', 'Mãe'), ('irmao', 'Irmão(ã)'), ('avo', 'Avô(ó)'), ('neto', 'Neto(a)'), ('outro', 'Outro')], max_length=20, verbose_name='Parentesco')),
                ('saude', models.JSONField(blank=True, default=list, verbose_name='Condições de Saúde')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('escolaridade', models.CharField(blank=True, default='', max_length=100, verbose_name='Escolaridade')),
                ('profissao', models.CharField(blank=True, default='', max_length=100, verbose_name='Profissão')),
                ('renda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda Mensal')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('upf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='sgp.upf', verbose_name='UPF')),
            ],
            options={
                'verbose_name': 'Membro da Família',
                'verbose_name_plural': 'Membros da Família',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['upf'], name='idx_membro_upf')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('parentesco', 'titular')), fields=('upf',), name='unique_titular_por_upf')],
            },
        ),
    ]
