# Generated by Django 6.0.4 on 2026-07-08 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_auditlog_and_notification'),
        ('sgp', '0002_membrofamilia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membrofamilia',
            name='cor_raca',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cor/Raça'),
        ),
        migrations.AddField(
            model_name='membrofamilia',
            name='escola',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='membrofamilia',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='membrofamilia',
            name='seguridade_social',
            field=models.JSONField(blank=True, default=list, verbose_name='Seguridade Social'),
        ),
        migrations.AddField(
            model_name='upf',
            name='agua',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Água'),
        ),
        migrations.AddField(
            model_name='upf',
            name='apelido',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Apelido'),
        ),
        migrations.AddField(
            model_name='upf',
            name='area_terra_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área da Terra (ha)'),
        ),
        migrations.AddField(
            model_name='upf',
            name='comunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upfs', to='sgp.comunidade', verbose_name='Comunidade'),
        ),
        migrations.AddField(
            model_name='upf',
            name='cor_raca',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cor/Raça'),
        ),
        migrations.AddField(
            model_name='upf',
            name='dispositivo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Dispositivo'),
        ),
        migrations.AddField(
            model_name='upf',
            name='energia',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Energia'),
        ),
        migrations.AddField(
            model_name='upf',
            name='escolaridade',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Escolaridade'),
        ),
        migrations.AddField(
            model_name='upf',
            name='internet',
            field=models.BooleanField(default=False, verbose_name='Acesso à Internet'),
        ),
        migrations.AddField(
            model_name='upf',
            name='pct',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='PCT'),
        ),
        migrations.AddField(
            model_name='upf',
            name='posse_terra',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Posse da Terra'),
        ),
        migrations.AddField(
            model_name='upf',
            name='seguridade_social',
            field=models.JSONField(blank=True, default=list, verbose_name='Seguridade Social'),
        ),
        migrations.AddField(
            model_name='upf',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AddIndex(
            model_name='upf',
            index=models.Index(fields=['comunidade'], name='idx_upf_comunidade'),
        ),
    ]
