# Generated by Django 6.0.4 on 2026-07-28 22:01

import apps.sgp.models.workplan
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_auditlog_and_notification'),
        ('sgp', '0002_seed_catalogos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlanAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numeração X.Y (ex: 1.1, 1.2).', max_length=10, validators=[apps.sgp.models.workplan.validate_numero_acao], verbose_name='Número')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('tipo_unidade', models.PositiveSmallIntegerField(choices=[(1, 'Seminário'), (2, 'Oficina'), (3, 'Curso / Capacitação'), (4, 'Plano'), (5, 'Relatório de pesquisas'), (6, 'Intercâmbio'), (7, 'Conteúdo audiovisual'), (8, 'Visita técnica'), (9, 'Encontro / Reunião'), (10, 'Unidade implementada'), (11, 'Família atendida'), (12, 'Outro')], verbose_name='Tipo de Unidade')),
                ('quantidade_planejada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantidade Planejada')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Unitário (R$)')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ação do Plano de Trabalho',
                'verbose_name_plural': 'Ações do Plano de Trabalho',
                'ordering': ['meta', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('tipo_atividade', models.CharField(choices=[('visita_tecnica', 'Visita técnica'), ('reuniao_comunitaria', 'Reunião comunitária'), ('oficina', 'Oficina'), ('intercambio', 'Intercâmbio'), ('curso_capacitacao', 'Curso/Capacitação'), ('dia_de_campo', 'Dia de campo'), ('seminario', 'Seminário'), ('encontro', 'Encontro'), ('dia_de_partilha', 'Dia de partilha'), ('atividade_interna', 'Atividade interna'), ('pesquisa_de_campo', 'Pesquisa de campo'), ('ater', 'Assistência técnica/ATER'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de Atividade')),
                ('forma_atuacao', models.CharField(choices=[('realizacao', 'Realização'), ('participacao', 'Participação'), ('apoio', 'Apoio'), ('articulacao', 'Articulação')], max_length=20, verbose_name='Forma de Atuação')),
                ('ambito', models.CharField(choices=[('municipal', 'Municipal'), ('microrregional', 'Microrregional'), ('estadual', 'Estadual'), ('supraestadual', 'Supraestadual')], max_length=20, verbose_name='Âmbito')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('parceiros', models.TextField(blank=True, default='', help_text='Lista de parceiros em texto livre. Futura versão integrará com Organizations.', verbose_name='Parceiros')),
                ('descricao_narrativa', models.TextField(verbose_name='Descrição Narrativa')),
                ('resultados_alcancados', models.TextField(blank=True, default='', verbose_name='Resultados Alcançados')),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('agendado', 'Agendado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('concluido_sem_evidencia', 'Concluído sem evidência'), ('adiada', 'Adiada'), ('nao_realizada', 'Não realizada'), ('cancelada', 'Cancelada')], db_index=True, default='planejado', max_length=30, verbose_name='Status')),
                ('justificativa', models.TextField(blank=True, default='', help_text='Obrigatório quando status = Não realizada ou Cancelada.', verbose_name='Justificativa')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('device_id', models.CharField(blank=True, default='', help_text='Identificador do dispositivo de origem (sync SCA).', max_length=100, verbose_name='Device ID')),
                ('uuid_local', models.UUIDField(blank=True, help_text='UUID gerado pelo dispositivo para idempotência no sync SCA.', null=True, unique=True, verbose_name='UUID Local')),
                ('comunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='sgp.comunidade', verbose_name='Comunidade')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('equipe_adicional', models.ManyToManyField(blank=True, related_name='atividades_equipe', to=settings.AUTH_USER_MODEL, verbose_name='Equipe Adicional')),
                ('membros_participantes', models.ManyToManyField(blank=True, related_name='atividades', to='sgp.membrofamilia', verbose_name='Membros Participantes')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='core.municipality', verbose_name='Município')),
                ('tecnico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
                ('upfs_participantes', models.ManyToManyField(blank=True, related_name='atividades', to='sgp.upf', verbose_name='UPFs Participantes')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='sgp.workplanacao', verbose_name='Ação do PT')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-data_inicio', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlanMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Número')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('ods_ids', models.JSONField(blank=True, default=list, help_text='Lista de IDs dos Objetivos de Desenvolvimento Sustentável (1–17).', verbose_name='ODS')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Meta do Plano de Trabalho',
                'verbose_name_plural': 'Metas do Plano de Trabalho',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='workplanacao',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='sgp.workplanmeta', verbose_name='Meta'),
        ),
        migrations.CreateModel(
            name='ActivityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_key', models.CharField(max_length=512, verbose_name='Key do arquivo (R2)')),
                ('arquivo_url', models.URLField(max_length=1024, verbose_name='URL pública do arquivo')),
                ('tipo', models.CharField(choices=[('lista_presenca', 'Lista de presença'), ('ata', 'Ata'), ('relatorio_parcial', 'Relatório parcial'), ('declaracao', 'Declaração'), ('contrato', 'Contrato'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome original do arquivo')),
                ('content_type', models.CharField(default='application/pdf', max_length=100, verbose_name='Content-Type')),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Tamanho em bytes')),
                ('data_documento', models.DateField(verbose_name='Data do documento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='sgp.activity', verbose_name='Atividade')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_atividade_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Documento da Atividade',
                'verbose_name_plural': 'Documentos da Atividade',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['activity', 'ativo'], name='idx_actdoc_activity_ativo')],
            },
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_key', models.CharField(max_length=512, verbose_name='Key do arquivo (R2)')),
                ('arquivo_url', models.URLField(max_length=1024, verbose_name='URL pública do arquivo')),
                ('legenda', models.CharField(blank=True, default='', max_length=255, verbose_name='Legenda')),
                ('data_hora_captura', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de captura')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='0 = capa da atividade. Usado para drag-and-drop no frontend.', verbose_name='Ordem')),
                ('content_type', models.CharField(default='image/jpeg', max_length=50, verbose_name='Content-Type')),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Tamanho em bytes')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='sgp.activity', verbose_name='Atividade')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_atividade_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Foto da Atividade',
                'verbose_name_plural': 'Fotos da Atividade',
                'ordering': ['ordem', 'criado_em'],
                'indexes': [models.Index(fields=['activity', 'ativa'], name='idx_actphoto_activity_ativa'), models.Index(fields=['activity', 'ordem'], name='idx_actphoto_activity_ordem')],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status'], name='idx_activity_status'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['municipio'], name='idx_activity_municipio'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['acao'], name='idx_activity_acao'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['tecnico_responsavel'], name='idx_activity_tecnico'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['data_inicio', 'data_fim'], name='idx_activity_datas'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['ativo'], name='idx_activity_ativo'),
        ),
        migrations.AddIndex(
            model_name='workplanmeta',
            index=models.Index(fields=['numero'], name='idx_wpmeta_numero'),
        ),
        migrations.AddIndex(
            model_name='workplanacao',
            index=models.Index(fields=['meta'], name='idx_wpacao_meta'),
        ),
        migrations.AddConstraint(
            model_name='workplanacao',
            constraint=models.UniqueConstraint(fields=('meta', 'numero'), name='unique_numero_acao_por_meta'),
        ),
    ]
