# Generated by Django 6.0.4 on 2026-09-30 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0002_seed_dados_iniciais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlosaRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda_id', models.CharField(db_index=True, help_text='Referência fraca a uma Demand do SGD (apps.sgd).', max_length=64, verbose_name='ID da Demanda')),
                ('demand_request_id', models.CharField(help_text='Referência fraca ao DemandRequest que recebeu o pagamento.', max_length=64, verbose_name='ID da Solicitação')),
                ('arlo_import_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID da importação Arlo')),
                ('valor_autorizado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor autorizado (R$)')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor pago (R$)')),
                ('excedente', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Excedente (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glosas_risco_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Risco de Glosa',
                'verbose_name_plural': 'Riscos de Glosa',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('demand_request_id', 'arlo_import_id'), name='uniq_glosarisk_solicitacao_import')],
            },
        ),
    ]
