# Generated by Django 6.0.4 on 2026-07-22 13:08

import apps.sgp.models.workplan
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0002_seed_catalogos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlanMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Número')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('ods_ids', models.JSONField(blank=True, default=list, help_text='Lista de IDs dos Objetivos de Desenvolvimento Sustentável (1–17).', verbose_name='ODS')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Meta do Plano de Trabalho',
                'verbose_name_plural': 'Metas do Plano de Trabalho',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlanAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numeração X.Y (ex: 1.1, 1.2).', max_length=10, validators=[apps.sgp.models.workplan.validate_numero_acao], verbose_name='Número')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('tipo_unidade', models.PositiveSmallIntegerField(choices=[(1, 'Seminário'), (2, 'Oficina'), (3, 'Curso / Capacitação'), (4, 'Plano'), (5, 'Relatório de pesquisas'), (6, 'Intercâmbio'), (7, 'Conteúdo audiovisual'), (8, 'Visita técnica'), (9, 'Encontro / Reunião'), (10, 'Unidade implementada'), (11, 'Família atendida'), (12, 'Outro')], verbose_name='Tipo de Unidade')),
                ('quantidade_planejada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantidade Planejada')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Unitário (R$)')),
                ('quantidade_realizada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantidade Realizada')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='sgp.workplanmeta', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Ação do Plano de Trabalho',
                'verbose_name_plural': 'Ações do Plano de Trabalho',
                'ordering': ['meta', 'numero'],
            },
        ),
        migrations.AddIndex(
            model_name='workplanmeta',
            index=models.Index(fields=['numero'], name='idx_wpmeta_numero'),
        ),
        migrations.AddIndex(
            model_name='workplanacao',
            index=models.Index(fields=['meta'], name='idx_wpacao_meta'),
        ),
        migrations.AddConstraint(
            model_name='workplanacao',
            constraint=models.UniqueConstraint(fields=('meta', 'numero'), name='unique_numero_acao_por_meta'),
        ),
    ]
