# Generated by Django 6.0.4 on 2026-10-08 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0003_arlo_glosa_risk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetIncreaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor solicitado (R$)')),
                ('valor_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor aprovado (R$)')),
                ('periodo_aplicacao', models.CharField(blank=True, default='', max_length=100, verbose_name='Período de aplicação')),
                ('demanda_id', models.CharField(blank=True, default=None, help_text='Referência fraca à Demand bloqueada (apps.sgd) — sem FK, no mesmo padrão de BudgetTransaction.demanda_id.', max_length=64, null=True, verbose_name='ID da Demanda')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('submetida', 'Submetida'), ('devolvida', 'Devolvida'), ('com_parecer', 'Com parecer'), ('aprovada', 'Aprovada'), ('aprovada_parcialmente', 'Aprovada parcialmente'), ('recusada', 'Recusada')], db_index=True, default='rascunho', max_length=24, verbose_name='Status')),
                ('parecer_articulador', models.TextField(blank=True, default='', verbose_name='Parecer do Articulador')),
                ('justificativa_decisao', models.TextField(blank=True, default='', verbose_name='Justificativa da decisão')),
                ('decidido_em', models.DateTimeField(blank=True, null=True, verbose_name='Decidido em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_recurso_extra', to='sgp.activity', verbose_name='Atividade que motivou o pedido')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisoes_recurso_extra', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por')),
                ('parecer_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pareceres_recurso_extra', to=settings.AUTH_USER_MODEL, verbose_name='Parecer por')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_recurso_extra', to='sgp.budgetrubrica', verbose_name='Rubrica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_recurso_extra', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Recurso Extra',
                'verbose_name_plural': 'Solicitações de Recurso Extra',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entre_rubricas', 'Entre rubricas'), ('entre_territorios', 'Entre territórios'), ('entre_niveis', 'Entre níveis')], max_length=20, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor (R$)')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('documento_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='Documento de respaldo')),
                ('saldo_origem_antes', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo da origem antes')),
                ('saldo_origem_depois', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo da origem depois')),
                ('saldo_destino_antes', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo do destino antes')),
                ('saldo_destino_depois', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo do destino depois')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('allocation_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_de_entrada', to='sgp.budgetallocation', verbose_name='Alocação de destino')),
                ('allocation_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_de_saida', to='sgp.budgetallocation', verbose_name='Alocação de origem')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remanejamentos_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('increase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='sgp.budgetincreaserequest', verbose_name='Solicitação de recurso extra')),
            ],
            options={
                'verbose_name': 'Remanejamento',
                'verbose_name_plural': 'Remanejamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='budgetincreaserequest',
            index=models.Index(fields=['status', '-criado_em'], name='idx_budgetincr_status_criado'),
        ),
        migrations.AddConstraint(
            model_name='budgetincreaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('valor_solicitado__gt', 0)), name='budgetincr_valor_positivo'),
        ),
    ]
