# Generated by OpenCode on 2026-07-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgp", "0003_add_campos_documentacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UPFDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("dap_caf", "DAP/CAF"),
                            ("contrato", "Contrato"),
                            ("laudo", "Laudo"),
                            ("identidade", "Identidade"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, default="", verbose_name="Descrição"),
                ),
                (
                    "arquivo_key",
                    models.CharField(max_length=512, verbose_name="Key do Arquivo"),
                ),
                (
                    "nome_original",
                    models.CharField(max_length=255, verbose_name="Nome Original"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="Content-Type"),
                ),
                (
                    "tamanho_bytes",
                    models.PositiveBigIntegerField(verbose_name="Tamanho em Bytes"),
                ),
                (
                    "data_documento",
                    models.DateField(verbose_name="Data do Documento"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_upf_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "upf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="sgp.upf",
                        verbose_name="UPF",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento da UPF",
                "verbose_name_plural": "Documentos da UPF",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(fields=["upf", "-criado_em"], name="idx_upfdoc_upf_criado"),
                    models.Index(fields=["arquivo_key"], name="idx_upfdoc_arquivo_key"),
                ],
            },
        ),
    ]
