# Generated by Django 6.0.4 on 2026-07-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0003_production'),
        ('sgp', '0003_workplanacao_activity_workplanmeta_workplanacao_meta_and_more'),
    ]

    operations = [
    ]
