# Generated by Django 6.0.4 on 2026-07-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0004_upfdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upf',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
    ]
