# Generated by Django 6.0.4 on 2026-08-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0005_activity_google_calendar_sync'),
        ('sgp', '0005_upf_membro_sync_sca'),
    ]

    operations = [
    ]
