# Generated by Django 6.0.4 on 2026-07-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgp", "0006_upfdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upf",
            name="cpf",
            field=models.CharField(max_length=11, verbose_name="CPF"),
        ),
    ]
