# Generated by Django 6.0.4 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgp", "0006_merge_20260804_1648"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("formulario_id", models.PositiveIntegerField(verbose_name="ID do formulário")),
                ("formulario_nome", models.CharField(max_length=255, verbose_name="Nome do formulário")),
                ("formulario_versao", models.CharField(max_length=50, verbose_name="Versão do formulário")),
                ("data_preenchimento", models.DateTimeField(verbose_name="Data de preenchimento")),
                ("respondente", models.CharField(blank=True, max_length=255, null=True, verbose_name="Respondente")),
                ("status", models.CharField(choices=[("rascunho", "Rascunho"), ("submetido", "Submetido")], default="rascunho", max_length=20, verbose_name="Status")),
                ("respostas_json", models.JSONField(default=dict, verbose_name="Respostas")),
                ("origem", models.CharField(choices=[("web", "Web"), ("sca", "SCA")], default="web", max_length=10, verbose_name="Origem")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("upf", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="form_responses", to="sgp.upf", verbose_name="UPF")),
            ],
            options={
                "verbose_name": "Resposta de formulário",
                "verbose_name_plural": "Respostas de formulário",
                "ordering": ["-data_preenchimento", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="formresponse",
            index=models.Index(fields=["upf", "-data_preenchimento"], name="idx_form_response_upf_data"),
        ),
    ]
