# Generated by Django 6.0.4 on 2026-08-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0007_form_response'),
        ('sgp', '0007_upf_activity_membro_sync_fields'),
    ]

    operations = [
    ]
