# Generated by Django 6.0.4 on 2026-08-25 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0007_upf_activity_membro_sync_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membrofamilia',
            index=models.Index(fields=['cpf'], name='idx_membro_cpf'),
        ),
        migrations.AddConstraint(
            model_name='membrofamilia',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf__gt', '')), fields=('cpf',), name='unique_cpf_global'),
        ),
    ]
