# Generated by Django 6.0.4 on 2026-08-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0008_membrofamilia_idx_membro_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrofamilia',
            name='cor_raca',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Branca'), (2, 'Preta'), (3, 'Parda'), (4, 'Amarela'), (5, 'Indígena')], null=True, verbose_name='Cor/Raça'),
        ),
        migrations.AlterField(
            model_name='membrofamilia',
            name='escolaridade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sem instrução'), (2, 'Fundamental incompleto'), (3, 'Fundamental completo'), (4, 'Médio incompleto'), (5, 'Médio completo'), (6, 'Superior incompleto'), (7, 'Superior completo')], null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='membrofamilia',
            name='genero',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Feminino'), (3, 'Não binário'), (4, 'Não informado')], null=True, verbose_name='Gênero'),
        ),
    ]
