# Generated by Django 6.0.4 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgp", "0008_merge_20260825_1424"),
    ]

    operations = [
        migrations.AddField(
            model_name="formresponse",
            name="contract_version",
            field=models.CharField(
                default="1.0",
                max_length=20,
                verbose_name="Versão do contrato",
            ),
        ),
        migrations.AddField(
            model_name="formresponse",
            name="resposta_id_origem",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Chave externa da resposta",
            ),
        ),
        migrations.AddConstraint(
            model_name="formresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resposta_id_origem__isnull", False)),
                fields=("origem", "resposta_id_origem"),
                name="uniq_form_response_origem_external_id",
            ),
        ),
    ]
