# Generated by Django 6.0.4 on 2026-08-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0009_formresponse_contract_and_origin_key'),
        ('sgp', '0011_renomeia_campos_membro'),
    ]

    operations = [
    ]
