# Generated by Django 6.0.4 on 2026-08-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0012_alter_comunidade_nome'),
        ('sgp', '0012_merge_20260827_1028'),
    ]

    operations = [
    ]
