# Generated by Django 6.0.4 on 2026-08-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0012_merge_20260827_1028'),
        ('sgp', '0012_merge_20260827_1042'),
    ]

    operations = [
    ]
