# Generated by Django 6.0.4 on 2026-08-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0013_merge_20260827_1213'),
        ('sgp', '0013_merge_20260828_0922'),
    ]

    operations = [
    ]
