# Generated by Django 6.0.4 on 2026-09-01 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0014_merge_20260828_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucesso', models.BooleanField(verbose_name='Sucesso')),
                ('mensagem_erro', models.TextField(blank=True, default='', verbose_name='Mensagem de erro')),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True, verbose_name='Ocorrido em')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_calendar_sync_events', to='sgp.activity', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Evento de Sincronização Google Calendar',
                'verbose_name_plural': 'Eventos de Sincronização Google Calendar',
                'ordering': ['-ocorrido_em'],
                'indexes': [models.Index(fields=['sucesso', 'ocorrido_em'], name='idx_gcalsync_sucesso_ocorrido')],
            },
        ),
    ]
