# Generated by Django 6.0.4 on 2026-09-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0015_encripta_campos_sensiveis_membro'),
        ('sgp', '0015_googlecalendarsyncevent'),
    ]

    operations = [
    ]
