# Generated by Django 6.0.4 on 2026-09-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0016_merge_20260903_1150'),
        ('sgp', '0017_seed_rubricas'),
    ]

    operations = [
    ]
