# Generated by Django 6.0.4 on 2026-09-04 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_power_bi_token'),
        ('sgp', '0019_budget_reserva_ugp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budgetallocation',
            name='ck_budget_allocation_nivel_consistente',
        ),
        migrations.AddConstraint(
            model_name='budgetallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado__isnull', True), ('nivel', 'nacional'), ('territorio__isnull', True)), models.Q(('estado__isnull', False), ('nivel', 'estadual'), ('territorio__isnull', True)), models.Q(('nivel', 'territorial'), ('territorio__isnull', False)), _connector='OR'), name='ck_budget_allocation_nivel_consistente'),
        ),
    ]
