# Generated by Django 6.0.4 on 2026-09-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0016_merge_20260903_1150'),
        ('sgp', '0019_cria_tecnicos_perfis_existentes'),
    ]

    operations = [
    ]
