# Generated by Django 6.0.4 on 2026-09-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0019_budget_reserva_ugp'),
        ('sgp', '0020_merge_20260904_1403'),
    ]

    operations = [
    ]
