# Generated by Django 6.0.4 on 2026-09-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0020_remove_budgetallocation_ck_budget_allocation_nivel_consistente_and_more'),
        ('sgp', '0021_merge_20260904_1424'),
    ]

    operations = [
    ]
