# Generated by Django 6.0.4 on 2026-09-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0022_merge_20260904_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
