# Generated by Django 6.0.4 on 2026-09-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0027_popula_quantidade_realizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgettransaction',
            name='tipo',
            field=models.CharField(choices=[('reserva', 'Reserva'), ('liberacao', 'Liberação'), ('execucao', 'Execução'), ('remanejamento', 'Remanejamento'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo'),
        ),
    ]
