# Generated by Django 6.0.4 on 2026-09-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0028_alter_budgettransaction_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplanacao',
            name='rubricas_previstas',
            field=models.ManyToManyField(blank=True, help_text='Rubricas orçamentárias esperadas para esta Ação — usado pelo SGD (RF23) pra alertar quando uma solicitação usa rubrica fora do previsto. Vazio = sem previsão cadastrada, não gera alerta.', related_name='acoes_previstas', to='sgp.budgetrubrica', verbose_name='Rubricas previstas'),
        ),
        migrations.AlterField(
            model_name='budgettransaction',
            name='demanda_id',
            field=models.CharField(blank=True, default=None, help_text='Referência fraca a uma Demand do SGD (apps.sgd) — sem FK de propósito, o motor não importa apps.sgd.', max_length=64, null=True, verbose_name='ID da Demanda'),
        ),
    ]
