# Generated by Django 6.0.4 on 2026-09-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0029_workplanacao_rubricas_previstas_and_more'),
        ('sgp', '0031_upf_ativa_para_ativo'),
    ]

    operations = [
    ]
