# Generated by Django 6.0.4 on 2026-09-26 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0032_merge_20260924_1756'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plano_trabalho', 'Plano de Trabalho'), ('atividades', 'Atividades'), ('upfs', 'UPFs')], max_length=20, verbose_name='Tipo')),
                ('formato', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=4, verbose_name='Formato')),
                ('filtros', models.JSONField(blank=True, default=dict, verbose_name='Filtros')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='pendente', max_length=12, verbose_name='Status')),
                ('progresso', models.PositiveSmallIntegerField(default=0, verbose_name='Progresso (%)')),
                ('erro', models.TextField(blank=True, default='', verbose_name='Erro')),
                ('total_registros', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de registros')),
                ('nome_arquivo', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do arquivo')),
                ('content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Content-Type')),
                ('conteudo', models.BinaryField(blank=True, null=True, verbose_name='Conteúdo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportacoes_sgp', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Exportação',
                'verbose_name_plural': 'Exportações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['solicitante', '-criado_em'], name='idx_exportjob_solicitante'), models.Index(fields=['expira_em'], name='idx_exportjob_expira_em')],
                'constraints': [models.CheckConstraint(condition=models.Q(('progresso__lte', 100)), name='ck_exportjob_progresso_ate_100')],
            },
        ),
    ]
