# Generated by Django 6.0.4 on 2026-09-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0033_exportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='enfileirado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enfileirado em'),
        ),
    ]
