# Generated by Django 6.0.4 on 2026-09-28 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0036_popula_submetas_indicadores'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workplanacao',
            name='unique_numero_acao_por_meta',
        ),
        migrations.AddField(
            model_name='workplanacao',
            name='valor_executado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Soma do valor pago nas demandas concluídas das Atividades da Ação. Mantido por apps.sgp.services.apuracao.recalcular_valor_executado.', max_digits=14, verbose_name='Valor Executado (R$)'),
        ),
        migrations.AlterField(
            model_name='workplanacao',
            name='data_fim',
            field=models.DateField(verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='workplanacao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='workplanacao',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='sgp.indicator', verbose_name='Indicador'),
        ),
        migrations.AlterField(
            model_name='workplanacao',
            name='meta',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='sgp.workplanmeta', verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='workplanacao',
            name='quantidade_realizada',
            field=models.PositiveIntegerField(default=0, help_text='Apurada conforme a forma de apuração do Indicador e mantida por apps.sgp.signals.workplan; na forma manual, lançada pela UGP. Use `manage.py verificar_progresso_acoes` para reconciliar.', verbose_name='Quantidade Realizada'),
        ),
        migrations.AlterField(
            model_name='workplanacao',
            name='submeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='sgp.workplansubmeta', verbose_name='Submeta'),
        ),
        migrations.AddIndex(
            model_name='workplanacao',
            index=models.Index(fields=['submeta'], name='idx_wpacao_submeta'),
        ),
        migrations.AddIndex(
            model_name='workplanacao',
            index=models.Index(fields=['indicador'], name='idx_wpacao_indicador'),
        ),
        migrations.AddConstraint(
            model_name='workplanacao',
            constraint=models.UniqueConstraint(fields=('submeta', 'numero'), name='unique_numero_acao_por_submeta'),
        ),
        migrations.RemoveField(
            model_name='workplanacao',
            name='tipo_unidade',
        ),
    ]
