# Generated by Django 6.0.4 on 2026-09-29 12:18

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.functions.comparison
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0037_acao_submeta_indicador_obrigatorios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplanacao',
            options={'ordering': ['meta', django.db.models.functions.comparison.Cast(models.Func(models.F('numero'), models.Value('.'), function='string_to_array'), output_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField()))], 'verbose_name': 'Ação do Plano de Trabalho', 'verbose_name_plural': 'Ações do Plano de Trabalho'},
        ),
        migrations.AlterModelOptions(
            name='workplansubmeta',
            options={'ordering': ['meta', django.db.models.functions.comparison.Cast(models.Func(models.F('numero'), models.Value('.'), function='string_to_array'), output_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField()))], 'verbose_name': 'Submeta do Plano de Trabalho', 'verbose_name_plural': 'Submetas do Plano de Trabalho'},
        ),
        migrations.AlterField(
            model_name='workplanacao',
            name='quantidade_planejada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='A quantidade planejada precisa ser maior que zero.')], verbose_name='Quantidade Planejada'),
        ),
        migrations.AlterField(
            model_name='workplanacao',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='O valor unitário não pode ser negativo.')], verbose_name='Valor Unitário (R$)'),
        ),
    ]
