# Generated by Django 6.0.4 on 2026-09-29 12:01

import django.contrib.postgres.fields
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0037_acao_submeta_indicador_obrigatorios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplanacao',
            options={'ordering': ['meta', django.db.models.functions.comparison.Cast(models.Func(models.F('numero'), models.Value('.'), function='string_to_array'), output_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField()))], 'verbose_name': 'Ação do Plano de Trabalho', 'verbose_name_plural': 'Ações do Plano de Trabalho'},
        ),
        migrations.AlterModelOptions(
            name='workplansubmeta',
            options={'ordering': ['meta', django.db.models.functions.comparison.Cast(models.Func(models.F('numero'), models.Value('.'), function='string_to_array'), output_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField()))], 'verbose_name': 'Submeta do Plano de Trabalho', 'verbose_name_plural': 'Submetas do Plano de Trabalho'},
        ),
    ]
