# Generated by Django 6.0.4 on 2026-08-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0002_syncevent_fields_conflictlog_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncevent',
            name='finalizado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Finalizado em'),
        ),
    ]
