# Generated by Django 6.0.4 on 2026-09-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0004_encripta_valores_conflict_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictlog',
            name='estrategia',
            field=models.CharField(choices=[('last_write_wins', 'Last-write-wins'), ('duplicate_rejeitado', 'Duplicata rejeitada'), ('exclusao_prevalece', 'Exclusão do servidor prevalece'), ('merge_automatico', 'Merge automático'), ('regra_negocio_rejeitada', 'Regra de negócio rejeitada')], default='last_write_wins', max_length=30, verbose_name='Estratégia aplicada'),
        ),
    ]
